// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYDQK2mZoUEUYsQ5t663DbN6-UPsqf1pk',
    appId: '1:207823148506:web:3de1389f2d264fc5cf5ce3',
    messagingSenderId: '207823148506',
    projectId: 'poolingfyp',
    authDomain: 'poolingfyp.firebaseapp.com',
    storageBucket: 'poolingfyp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH8k-sDNdVaehkNoEljiAlVE6xalIrXqA',
    appId: '1:207823148506:android:e1dfc61e9b61cce9cf5ce3',
    messagingSenderId: '207823148506',
    projectId: 'poolingfyp',
    storageBucket: 'poolingfyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKav7o0ti7MfE0ZNlj92tz112GlLztZ_Q',
    appId: '1:207823148506:ios:5b1ba7f7ed148eaecf5ce3',
    messagingSenderId: '207823148506',
    projectId: 'poolingfyp',
    storageBucket: 'poolingfyp.appspot.com',
    iosBundleId: 'com.fyp.poolingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKav7o0ti7MfE0ZNlj92tz112GlLztZ_Q',
    appId: '1:207823148506:ios:f4eefc970d7147dacf5ce3',
    messagingSenderId: '207823148506',
    projectId: 'poolingfyp',
    storageBucket: 'poolingfyp.appspot.com',
    iosBundleId: 'com.fyp.poolingapp.RunnerTests',
  );
}
